"use client";
import { useEffect, useRef, useState } from "react";
import maplibregl, { GeoJSONSource } from "maplibre-gl";
import type { Analysis } from "@/types";
export default function ClimateMap({ analysis }: { analysis: Analysis }) {
 const container = useRef<HTMLDivElement>(null); const map = useRef<maplibregl.Map | null>(null); const data = useRef(analysis); const [error, setError] = useState("");
 useEffect(() => { data.current = analysis; if (map.current?.isStyleLoaded()) (map.current.getSource("rain") as GeoJSONSource)?.setData(analysis.map); }, [analysis]);
 useEffect(() => { if (!container.current) return; try { const instance = new maplibregl.Map({ container: container.current, style: { version: 8, sources: {}, layers: [{ id: "background", type: "background", paint: { "background-color": "#e9f0eb" } }] }, bounds: [[21,-12],[52,24]], fitBoundsOptions: { padding: 20 }, attributionControl: false }); map.current = instance;
 instance.addControl(new maplibregl.NavigationControl(), "top-right"); instance.addControl(new maplibregl.AttributionControl({ customAttribution: "Natural Earth · public domain | Synthetic rainfall" }));
 instance.on("load", () => { instance.addSource("rain", { type: "geojson", data: data.current.map }); instance.addLayer({ id: "rain", type: "fill", source: "rain", paint: { "fill-color": ["interpolate", ["linear"], ["get","value"], -30,"#ba7751",0,"#f3efc6",25,"#c1dcba",50,"#62ad92",80,"#2c8276",120,"#164e63"], "fill-opacity": 0.88 } }); instance.addSource("countries", { type: "geojson", data: "/countries.geojson" }); instance.addLayer({ id: "country-fill", type: "fill", source: "countries", paint: { "fill-color": "#9ea998", "fill-opacity": 0.09 } }); instance.addLayer({ id: "country-boundaries", type: "line", source: "countries", paint: { "line-color": "#526858", "line-width": 1.2 } }); });
 instance.on("click", "rain", (event) => { const value = event.features?.[0]?.properties?.value; new maplibregl.Popup().setLngLat(event.lngLat).setText("Synthetic cell: " + value + (data.current.selection.layer === "anomaly" ? " %" : " mm")).addTo(instance); });
 const resize = new ResizeObserver(() => instance.resize()); resize.observe(container.current); return () => { resize.disconnect(); instance.remove(); map.current = null; }; } catch { setError("WebGL map unavailable. Download the PNG map to view this product."); } }, []);
 return <div className="map-shell"><div ref={container} className="map" aria-label="Interactive Greater Horn climate map"/>{error && <div className="map-error">{error}</div>}<div className="map-caption"><strong>GREATER HORN OF AFRICA</strong><span>{analysis.selection.layer} · {analysis.provenance.model as string}</span></div><div className="map-legend"><span>{analysis.selection.layer === "anomaly" ? "Anomaly (%)" : "Rainfall / error (mm)"}</span><div className="legend-gradient"/><div className="legend-ticks"><span>0</span><span>25</span><span>50</span><span>80</span><span>120+</span></div></div></div>;
}
