"use client";
import {useEffect,useState} from "react";
import {Play} from "lucide-react";
import type {Analysis,Config,Selection} from "@/types";
import {mutate,request} from "@/services/api";
export default function Workflow({view,selection,config}:{view:string;selection:Selection;analysis:Analysis;config:Config|null;refresh:()=>void}) {
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(""),[pending,setPending]=useState(false);
 useEffect(()=>{setRows([]);setError("");const load=()=>{if(view==="jobs"||view==="health")request<any>(view==="jobs"?"/jobs":"/health").then(data=>setRows(view==="jobs"?data:Object.entries(data.components).map(([name,status])=>({name,status})))).catch(e=>setError(e.message));};load();if(view==="jobs"){const timer=setInterval(load,2500);return()=>clearInterval(timer);}},[view]);
 if(view==="models") return <section className="panel"><div className="panel-head"><h2>Model registry</h2></div><div className="product-grid">{config?.models.map(m=><div className="product-card" key={m.model_id}><span className={"badge "+(m.status==="production"?"green":"amber")}>{m.status}</span><h3>{m.model_name}</h3><p>Version {m.version} · {m.model_type}</p><dl><dt>Feature schema</dt><dd>{m.feature_schema}</dd><dt>Training period</dt><dd>{m.training_period}</dd><dt>Artifact</dt><dd>{m.artifact_path??"Built-in demonstration"}</dd></dl><details><summary>View metadata</summary><pre>{JSON.stringify(m,null,2)}</pre></details></div>)}</div></section>;
 if(view==="jobs") return <section className="panel"><div className="panel-head"><div><h2>Pipeline jobs</h2><p>Simulated afterok stages · status updates every few seconds</p></div><button className="button primary" disabled={pending} onClick={async()=>{setPending(true);try{await mutate("/jobs",selection);setRows(await request("/jobs"));}catch(e){setError((e as Error).message);}finally{setPending(false);}}}><Play size={14}/>Run demo pipeline</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="table-scroll"><table><thead><tr><th>JOB ID</th><th>CYCLE</th><th>STAGE</th><th>EXECUTOR</th><th>STATUS</th><th>LOGS</th></tr></thead><tbody>{rows.map(j=><tr key={j.id}><td>{j.id.slice(0,8)}</td><td>{j.cycle}</td><td>{j.stage}</td><td>{j.executor}</td><td><span className={"badge "+(j.status==="success"?"green":"amber")}>{j.status}</span></td><td><details><summary>View</summary><pre>{j.log}</pre></details></td></tr>)}</tbody></table></div>{!rows.length&&<p className="prose">Run a demonstration pipeline to create tracked jobs.</p>}</section>;
 if(view==="health")return <section className="panel"><div className="panel-head"><h2>System components</h2></div><div className="checks">{rows.map(r=><div key={r.name}><span>{r.name}</span><strong>{String(r.status)}</strong></div>)}</div></section>;
 if(view==="settings")return <section className="panel"><div className="panel-head"><h2>Scientific configuration</h2></div><pre>{JSON.stringify(config?.science,null,2)}</pre><p className="prose">Versioned configuration is managed in Git. Operational data and model artifacts are mounted externally.</p></section>;
 return <section className="panel"><div className="panel-head"><h2>{view}</h2></div><p className="prose">Validated forecast context is ready. Workflow integration follows Phase 1 checks.</p></section>;
}
